name: CI

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macOS-latest, windows-latest]
        python: [3.9]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - if: matrix.os != 'ubuntu-latest'
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: stable
            override: true
      - if: matrix.os == 'ubuntu-latest'
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-musl
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: rust-cargo
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
      - name: py-deps
        run: |
          pip install --upgrade pip
          pip install cffi maturin
      - name: py-install
        run: |
          maturin build --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
            name: wheel
            path: target/wheels
        

